### ISSUE TITLE
ゴミ箱の詳細リストを表示

### ISSUE THREAD

**Issue by negi1232** [negi1232/SALVARE#8]
表示するもの

- 住所
- 報酬
- 重さ
- ゴミ箱の容量
- 依頼主
- 外観(ゴミ場所を俯瞰した写真)

**Comment by CanIyu** [comment]
ゴミ箱の最大容積は現時点の貯まり度を把握するためのものという認識であってますか？

**Comment by CanIyu** [comment]
@negi1232 上記のものを人間が見れるように表示しました。
外観については、画像を直貼りしているのでコミュニケーションが必要そうです。
